### ISSUE TITLE
可能会内存溢出

### ISSUE THREAD

**Issue by zhuichen** [PeterMen/elasticsearch-analysis-ik#1]

**Comment by zhuichen** [comment]
如果不同索引，你加载不同字典，有一个基本的汉字字典库是27w条记录，如果100个索引，意味着你要加载2700w到内存，内存就会溢出，所以我觉得需要优化存储结构

**Comment by PeterMen** [comment]
你说的这个27W的字典不应该是每个索引加载一份，应该是一个公共字典，只加载一份才对，就像IK里的main_dic一样
